spring:
  datasource:
    url: jdbc:mysql://1.1.1.2:3306/project_a_prod
    username: prod_user
    password: prod_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

# 生产环境配置
server:
  port: 8080

logging:
  level:
    com.example: WARN
    root: WARN
