spring:
  datasource:
    url: jdbc:mysql://1.1.1.1:3307/project_a_test
    username: test_user
    password: test_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

# 测试环境配置
server:
  port: 8082

logging:
  level:
    com.example: INFO
